### ISSUE TITLE
关于楼主提到的第三个问题

### ISSUE THREAD

**Issue by splm** [dyguests/AndroidGroovy#1]
我的解决方案是直接在gradle中设置Java的源码文件为重命名的groovy文件夹的路径。
然后还有一个小问题，就是groovy在对于有参数的抽象类的构造方法，用闭包的方法如何实现？
比如abstract class Person(A a ,B b)，我要如何使用闭包来完成实现？

**Comment by dyguests** [comment]
非常感谢.
闭包实现的问题我也不清楚啦.SORRY

**Comment by splm** [comment]
嗯，好的。我也在做基于groovy开发的一个Android的小demo。对于一些其中也用到了一些闭包的功能，哥们也可以关注一下。我最近也要上传了。哈哈~~

**Comment by dyguests** [comment]
好的,到时求github项目地址.

我给你说:闭包,赞!
